// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/shilongqi/Code/Learn/talking-code/background/09. 权限控制与首页/src/models/adminModel';
import model_2 from '/Users/shilongqi/Code/Learn/talking-code/background/09. 权限控制与首页/src/models/typeModel';

export const models = {
model_1: { namespace: 'adminModel', model: model_1 },
model_2: { namespace: 'typeModel', model: model_2 },
} as const
