// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/shilongqi/Code/Learn/talking-code/background/09. 权限控制与首页/src/models/global';
import model_2 from '/Users/shilongqi/Code/Learn/talking-code/background/09. 权限控制与首页/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'global', model: model_1 },
model_2: { namespace: '@@initialState', model: model_2 },
} as const
